import type { CampaignPreparation } from './campaignPreparationTypes';

export const campaignPreparationFixture: CampaignPreparation = {
  contract_version: 'crm_campaign_prepare.v1',
  campaign: {
    id: '22222222-2222-4222-8222-222222222222',
    status: 'draft',
    channel: 'whatsapp',
    template: {
      id: '11111111-1111-4111-8111-111111111111',
      key: 'municipal_update',
      message_template_registry_id: 31,
    },
    scheduled_for_utc: null,
    created_at: '2026-08-02T12:00:00+00:00',
    idempotent_replay: false,
  },
  preview: {
    subject: null,
    body: 'Hola vecino, hay una novedad municipal.',
    strict_variable_contract: true,
    contains_unresolved_variables: false,
  },
  audience: {
    requested: 3,
    unique_requested: 3,
    resolved: 3,
    eligible: 2,
    excluded: 1,
    unresolved: 0,
    duplicates_ignored: 0,
    exclusion_counts: {
      opt_out: 1,
      consent_missing: 0,
      missing_whatsapp: 0,
      missing_email: 0,
      frequency_window: 0,
    },
    rate_limit_policy: {
      max_per_week: 2,
      min_interval_hours: 24,
      legacy_records_are_conservative_guards_only: true,
    },
    consent_policy: {
      purpose: 'marketing',
      explicit_opt_in_required: true,
    },
  },
  readiness: {
    preview_valid: true,
    audience_evaluated: true,
    consent_evaluated: true,
    rate_limit_evaluated: true,
    provider_template_approval_valid: true,
    provider_template_ready: true,
    transport_readiness_checked: false,
    production_send_allowed: false,
    blockers: [
      'transport_readiness_not_checked',
      'campaign_dispatch_not_authorized',
    ],
  },
  queue: {
    state: 'held',
    dispatch_authorized: false,
    receipts: [
      {
        intent_id: '33333333-3333-4333-8333-333333333331',
        contact_id: 'contact-1',
        queue_status: 'held',
        exclusion_reason: null,
        transport_status: 'not_attempted',
        attempt_count: 0,
        provider_receipt_present: false,
      },
      {
        intent_id: '33333333-3333-4333-8333-333333333332',
        contact_id: 'contact-2',
        queue_status: 'held',
        exclusion_reason: null,
        transport_status: 'not_attempted',
        attempt_count: 0,
        provider_receipt_present: false,
      },
      {
        intent_id: '33333333-3333-4333-8333-333333333333',
        contact_id: 'contact-3',
        queue_status: 'excluded',
        exclusion_reason: 'opt_out',
        transport_status: 'not_attempted',
        attempt_count: 0,
        provider_receipt_present: false,
      },
    ],
    transport_outcomes: {
      not_attempted: 3,
      unknown: 0,
      accepted: 0,
      sent: 0,
      delivered: 0,
      read: 0,
      failed: 0,
    },
  },
  side_effects: {
    campaigns_created: 1,
    queue_receipts_created: 3,
    notifications_queued: 0,
    provider_calls_performed: false,
    messages_sent: 0,
  },
};
