import type { InterviewResumeEnvelope } from './interviewsTypes';

export const interviewResumeFixture: InterviewResumeEnvelope = {
  ok: true,
  contract_version: 'assessment.interviews.api.v1',
  resume: {
    contract_version: 'interview.session_resume.v1',
    tenant_id: 7,
    session: {
      id: 42,
      tenant_id: 7,
      assessment_case_id: 12,
      program_version_id: 3,
      status: 'active',
      channel: 'whatsapp',
      interviewer_user_id: 9,
      subject_channel_identity: {
        binding_id: 31,
        identity_version: 1,
        chat_session_id: 'chat-session-1',
        channel_identity_pinned: true,
        civil_identity_verified: false,
      },
      scheduled_for: '2026-08-02T12:00:00Z',
      consent: {
        granted: true,
        policy_version: 'admissions-consent.v1',
        text_sha256: 'c'.repeat(64),
        recorded_at: '2026-08-02T12:01:00Z',
        source: 'whatsapp',
        attestation_kind: 'participant_event',
        evidence_provider: 'twilio',
        evidence_ref: 'provider-event-1',
        evidence_sha256: 'd'.repeat(64),
        evidence_captured_at: '2026-08-02T12:01:00Z',
        attested_by_user_id: 9,
        verified_against_program_version: true,
        text_snapshot_verified: true,
        participant_evidence_bound: true,
        participant_evidence_verified: true,
        channel_identity_evidence_verified: true,
        consent_text_delivery_evidence_verified: true,
        civil_identity_verified: false,
        proof_status: 'expected_channel_delivery_and_action_verified',
      },
      started_at: '2026-08-02T12:02:00Z',
      completed_at: null,
      evidence_count: 1,
    },
    case: {
      id: 12,
      status: 'interview_in_progress',
      program_id: 2,
      program_version_id: 3,
      source_channel: 'whatsapp',
    },
    program_snapshot: {
      id: 3,
      program_id: 2,
      version_number: 1,
      definition_hash: 'e'.repeat(64),
      definition: {
        contract_version: 'interview.definition.v1',
        sections: [],
      },
      runtime_contract: 'interview.definition.v1',
      immutable: true,
    },
    steps: [
      {
        step_ref: 'profile.motivation',
        section_id: 'profile',
        question_id: 'motivation',
        prompt: 'Contanos por qué elegiste esta institución.',
        required: true,
        evidence_types: ['audio', 'transcript'],
        ordinal: 1,
      },
      {
        step_ref: 'profile.document',
        section_id: 'profile',
        question_id: 'document',
        prompt: 'Adjuntá una imagen legible del documento solicitado.',
        required: true,
        evidence_types: ['image', 'file'],
        ordinal: 2,
      },
    ],
    progress: {
      contract_version: 'interview.progress.v1',
      mode: 'step_evidence_v1',
      completion_gate_enforced: true,
      total_steps: 2,
      required_steps: 2,
      completed_steps: 1,
      completed_required_steps: 1,
      pending_required_steps: 1,
      percent: 50,
      required_steps_satisfied: false,
      completed_step_refs: ['profile.motivation'],
      pending_required_step_refs: ['profile.document'],
      step_evidence_counts: {
        'profile.motivation': 1,
        'profile.document': 0,
      },
      evidence_count: 1,
      evidence_by_type: {
        audio: 1,
        image: 0,
        file: 0,
        transcript: 0,
        location: 0,
        structured: 0,
      },
      last_checkpoint_at: '2026-08-02T12:03:00Z',
      last_checkpoint_source: 'evidence',
      current_step: {
        step_ref: 'profile.document',
        section_id: 'profile',
        question_id: 'document',
        prompt: 'Adjuntá una imagen legible del documento solicitado.',
        required: true,
        evidence_types: ['image', 'file'],
        ordinal: 2,
      },
      session_status: 'active',
      can_complete: false,
    },
    evidence: [
      {
        contract_version: 'interview.evidence.v1',
        id: 101,
        tenant_id: 7,
        interview_session_id: 42,
        evidence_type: 'audio',
        source_channel: 'whatsapp',
        storage_ref: 'storage:private-audio-object',
        content_sha256: 'a'.repeat(64),
        provenance: {
          provider: 'twilio',
          source_channel: 'whatsapp',
          captured_at: '2026-08-02T12:03:00Z',
          mime_type: 'audio/ogg',
          step_ref: 'profile.motivation',
        },
        size_bytes: 2048,
        created_at: '2026-08-02T12:03:00Z',
      },
    ],
    supported_evidence_types: [
      'audio',
      'image',
      'file',
      'transcript',
      'location',
      'structured',
    ],
    next_action: 'capture_step',
    available_actions: ['add_evidence'],
    resumable: true,
    updated_at: '2026-08-02T12:03:00Z',
  },
};
