import React from 'react';
import {act,cleanup,fireEvent,render,screen,waitFor,within} from '@testing-library/react';
import {afterEach,beforeEach,describe,expect,it,vi} from 'vitest';
const mocks=vi.hoisted(()=>({fetch:vi.fn(),routing:vi.fn(),ready:vi.fn(),user:{id:1,rol:'superadmin',tenant_slug:'actor-home'},verified:true,profile:true,search:'?tenant_slug=selected-org',tenant:{id:31,slug:'selected-org',tipo:'municipio'}}));
vi.mock('@/hooks/useUser',()=>({useUser:()=>({user:mocks.user,loading:false,hasVerifiedSession:mocks.verified,organizationProfileVerified:mocks.profile})}));
vi.mock('@/context/TenantContext',()=>({useTenant:()=>({tenant:mocks.tenant,isLoadingTenant:false,tenantError:null})}));
vi.mock('react-router-dom',async original=>({...await original<typeof import('react-router-dom')>(),useNavigate:()=>vi.fn(),useLocation:()=>({pathname:'/municipal/categorias',search:mocks.search})}));
vi.mock('@/utils/api',async original=>({...await original<typeof import('@/utils/api')>(),apiFetch:(...args:unknown[])=>mocks.fetch(...args)}));
vi.mock('@/utils/backendBootstrapGate',()=>({ensureBackendRuntimeReady:()=>mocks.ready()}));
vi.mock('@/api/v2/saas',async original=>({...await original<typeof import('@/api/v2/saas')>(),getEmployeeRoutingV2:(...args:unknown[])=>mocks.routing(...args)}));
import CategoryManagementPage from './CategoryManagementPage';
import {ApiError} from '@/utils/api';
const routing=()=>({dimensions:{categorias:['Alumbrado','Arbolado']},employees:[],queues:{unassigned_count:55},raw:{tenant:{id:31,slug:'selected-org'}}});
const deferred=()=>{let resolve!:(v:any)=>void;return {promise:new Promise<any>(r=>{resolve=r;}),resolve:(v:any)=>resolve(v)};};
beforeEach(()=>{mocks.fetch.mockReset().mockResolvedValue({categorias:[]});mocks.routing.mockReset().mockResolvedValue(routing());mocks.ready.mockReset().mockResolvedValue(undefined);mocks.user={id:1,rol:'superadmin',tenant_slug:'actor-home'};mocks.verified=true;mocks.profile=true;mocks.search='?tenant_slug=selected-org';mocks.tenant={id:31,slug:'selected-org',tipo:'municipio'};});
afterEach(cleanup);
describe('catalog preparation from selected routing topics',()=>{
 it('creates only the reviewed name, with one POST, then links to scoped responsibilities',async()=>{
  render(<CategoryManagementPage/>);fireEvent.click(await screen.findByRole('button',{name:'Revisar y crear categoría: Alumbrado'}));const dialog=screen.getByRole('dialog',{name:'Crear categoría'});
  expect(within(dialog).getByLabelText('Nombre')).toHaveValue('Alumbrado');expect(screen.queryByText('Crear regla')).not.toBeInTheDocument();fireEvent.change(within(dialog).getByLabelText('Nombre'),{target:{value:'Iluminación pública'}});
  mocks.fetch.mockImplementation(async (_path,options)=>options.method==='POST'?{id:20,nombre:options.body.nombre}:{categorias:[{id:20,nombre:'Iluminación pública'}]});
  const save=within(dialog).getByRole('button',{name:'Guardar'});fireEvent.click(save);fireEvent.click(save);await screen.findByText(/La categoría «Iluminación pública» está en el catálogo/);
  const writes=mocks.fetch.mock.calls.filter(call=>call[1].method==='POST');expect(writes).toHaveLength(1);expect(writes[0]).toEqual(['/municipal/categorias',expect.objectContaining({body:{nombre:'Iluminación pública'},tenantSlug:'selected-org',singleAttempt:true,allowStartupRecovery:false,omitEntityToken:true,isWidgetRequest:false})]);expect(screen.getByRole('link',{name:'Revisar responsables'})).toHaveAttribute('href','/empleados?tenant_slug=selected-org');
 });
 it('keeps an edited draft and accessible error after a denied save without replay',async()=>{
  render(<CategoryManagementPage/>);fireEvent.click(await screen.findByRole('button',{name:'Revisar y crear categoría: Alumbrado'}));const dialog=screen.getByRole('dialog');fireEvent.change(within(dialog).getByLabelText('Nombre'),{target:{value:'Nombre revisado'}});
  mocks.fetch.mockRejectedValueOnce(new ApiError('Denied',403));fireEvent.click(within(dialog).getByRole('button',{name:'Guardar'}));await within(dialog).findByRole('alert');expect(within(dialog).getByLabelText('Nombre')).toHaveValue('Nombre revisado');expect(mocks.fetch.mock.calls.filter(call=>call[1].method==='POST')).toHaveLength(1);
  fireEvent.click(within(dialog).getByRole('button',{name:'Cancelar'}));fireEvent.click(screen.getByRole('button',{name:'Crear categoria'}));expect(screen.getByLabelText('Nombre')).toHaveValue('Nombre revisado');
 });
 it('blocks another write after an unconfirmed receipt and permits only an explicit catalog check',async()=>{
  render(<CategoryManagementPage/>);fireEvent.click(await screen.findByRole('button',{name:'Revisar y crear categoría: Alumbrado'}));fireEvent.click(within(screen.getByRole('dialog')).getByRole('button',{name:'Guardar'}));
  await screen.findByText(/no pudimos confirmar la categoría en el catálogo/);expect(screen.queryByText(/La categoría «/)).not.toBeInTheDocument();expect(screen.getByLabelText('Nombre')).toHaveValue('Alumbrado');const save=screen.getByRole('button',{name:'Guardar'});expect(save).toBeDisabled();fireEvent.click(save);expect(mocks.fetch.mock.calls.filter(call=>call[1].method==='POST')).toHaveLength(1);
  mocks.fetch.mockResolvedValueOnce({categorias:[{id:22,nombre:'Alumbrado'}]});fireEvent.click(screen.getByRole('button',{name:'Comprobar catálogo'}));await screen.findByText(/La categoría «Alumbrado» está en el catálogo/);expect(mocks.fetch.mock.calls.filter(call=>call[1].method==='POST')).toHaveLength(1);
 });
 it('retires a pending save after the actor changes without showing its receipt or refreshing old scope',async()=>{
  const view=render(<CategoryManagementPage/>);fireEvent.click(await screen.findByRole('button',{name:'Revisar y crear categoría: Alumbrado'}));const pending=deferred();mocks.fetch.mockReturnValueOnce(pending.promise);fireEvent.click(within(screen.getByRole('dialog')).getByRole('button',{name:'Guardar'}));const options=mocks.fetch.mock.calls.at(-1)![1];
  mocks.user={...mocks.user,id:2};view.rerender(<CategoryManagementPage/>);await screen.findByRole('button',{name:'Revisar y crear categoría: Alumbrado'});expect(options.isCurrent()).toBe(false);await act(async()=>{pending.resolve({id:20});await pending.promise;});expect(screen.queryByText(/La categoría «/)).not.toBeInTheDocument();expect(screen.queryByRole('dialog')).not.toBeInTheDocument();
 });
 it.each(['unverified','foreign','employee'])('does not load a private catalog for %s authority',kind=>{
  if(kind==='unverified')mocks.profile=false;if(kind==='foreign')mocks.user={id:2,rol:'admin_municipio',tenant_slug:'actor-home'};if(kind==='employee')mocks.user={id:3,rol:'empleado',tenant_slug:'selected-org'};render(<CategoryManagementPage/>);expect(mocks.fetch).not.toHaveBeenCalled();expect(mocks.routing).not.toHaveBeenCalled();
 });
 it('does not grant team administration to a catalog manager',async()=>{mocks.user={id:4,rol:'catalog_manager',tenant_slug:'selected-org'};render(<CategoryManagementPage/>);await screen.findByRole('button',{name:'Revisar y crear categoría: Alumbrado'});expect(screen.queryByRole('link',{name:'Ver equipo y responsables'})).not.toBeInTheDocument();});
 it('does not invent coverage counts if routing is unavailable',async()=>{mocks.routing.mockRejectedValue(new Error('Unavailable'));render(<CategoryManagementPage/>);await screen.findByText('Todavia no hay categorias configuradas');expect(screen.getAllByText('No informado')).toHaveLength(3);});
 it('distinguishes compatible current demand from unknown coverage without persisting topics',async()=>{
  const model=routing();(model.raw as any).category_inventory={contract_version:'employee.category_inventory.v1',tenant:{id:31,slug:'selected-org'},population:'open_tickets',viewer_scope:'tenant_dispatch',coverage_basis:'employees_eligible_for_at_least_one_current_open_ticket',read_only:true,writes_performed:false,summary:{persisted_categories:0,redacted_persisted_categories:0,detected_topics:1,open_count:55,unassigned_count:55},items:[{key:'alumbrado',label:'Alumbrado',persisted_category_ids:[],source_types:['open_tickets'],open_count:55,unassigned_count:55,eligible_employee_count:0,coverage_reason_code:'current_open_ticket_eligibility'},{key:'arbolado',label:'Arbolado',persisted_category_ids:[],source_types:['municipio_baseline_taxonomy'],open_count:0,unassigned_count:0,eligible_employee_count:null,coverage_reason_code:'no_current_open_ticket_evidence'}]};mocks.routing.mockResolvedValue(model);render(<CategoryManagementPage/>);
  await screen.findByText('55 casos abiertos · 55 sin responsable');expect(screen.getByText('0 personas compatibles con al menos un caso')).toBeVisible();expect(screen.getByText('Compatibilidad no verificada: sin demanda actual')).toBeVisible();expect(mocks.fetch.mock.calls.some(call=>call[1].method==='POST')).toBe(false);
 });
 it('accepts a mixed inventory where only open demand outside the catalog is a detected topic',async()=>{
  mocks.fetch.mockResolvedValue({categorias:[{id:15,nombre:'Tema persistido'}]});const model=routing();(model.raw as any).category_inventory={contract_version:'employee.category_inventory.v1',tenant:{id:31,slug:'selected-org'},population:'open_tickets',viewer_scope:'tenant_dispatch',coverage_basis:'employees_eligible_for_at_least_one_current_open_ticket',read_only:true,writes_performed:false,summary:{persisted_categories:1,redacted_persisted_categories:0,detected_topics:1,open_count:5,unassigned_count:3},items:[{key:'persisted',label:'Tema persistido',persisted_category_ids:[15],source_types:['tenant_category_catalog','open_tickets'],open_count:2,unassigned_count:0,eligible_employee_count:1,coverage_reason_code:'current_open_ticket_eligibility'},{key:'configured',label:'Tema configurado',persisted_category_ids:[],source_types:['tenant_config'],open_count:0,unassigned_count:0,eligible_employee_count:null,coverage_reason_code:'no_current_open_ticket_evidence'},{key:'observed',label:'Demanda nueva',persisted_category_ids:[],source_types:['open_tickets'],open_count:3,unassigned_count:3,eligible_employee_count:0,coverage_reason_code:'current_open_ticket_eligibility'}]};mocks.routing.mockResolvedValue(model);render(<CategoryManagementPage/>);
  await screen.findByText('2 casos abiertos · 0 sin responsable');expect(screen.getByText('3 casos abiertos · 3 sin responsable')).toBeVisible();expect(screen.getByRole('button',{name:'Editar categoría: Tema persistido'})).toBeEnabled();expect(screen.getByRole('button',{name:'Revisar y crear categoría: Tema configurado'})).toBeEnabled();expect(screen.getByRole('button',{name:'Revisar y crear categoría: Demanda nueva'})).toBeEnabled();expect(screen.getByText('Compatibilidad no verificada: sin demanda actual')).toBeVisible();expect(mocks.fetch.mock.calls.some(call=>call[1].method==='POST')).toBe(false);
 });
 it('ignores a foreign inventory envelope rather than presenting it as current demand',async()=>{const model=routing();(model.raw as any).category_inventory={contract_version:'employee.category_inventory.v1',tenant:{id:99,slug:'foreign'},items:[{label:'FOREIGN_PRIVATE_TOPIC'}]};mocks.routing.mockResolvedValue(model);render(<CategoryManagementPage/>);await screen.findByRole('button',{name:'Revisar y crear categoría: Alumbrado'});expect(screen.queryByText('FOREIGN_PRIVATE_TOPIC')).not.toBeInTheDocument();});
});
